### ISSUE TITLE
No Resume here

### ISSUE THREAD

**Issue by araman18** [Nicholas227/Resume#1]
Says there is a Resume, isn't one. Can anyone fix this ?

**Comment by Nicholas227** [comment]
Impromperly formatted, please submit again.

**Comment by Nicholas227** [comment]
Impromperly formatted, please submit again.

**Comment by Nicholas227** [comment]
Impromperly formatted, please submit again.

**Comment by Nicholas227** [comment]
Impromperly formatted, please submit again.

**Comment by Nicholas227** [comment]
Impromperly formatted, please submit again.

**Comment by Nicholas227** [comment]
Impromperly formatted, please submit again.

**Comment by Nicholas227** [comment]
Impromperly formatted, please submit again.

**Comment by Nicholas227** [comment]
Impromperly formatted, please submit again.

**Comment by Nicholas227** [comment]
Impromperly formatted, please submit again.

**Comment by Nicholas227** [comment]
Impromperly formatted, please submit again.

**Comment by Nicholas227** [comment]
Impromperly formatted, please submit again.

**Comment by Nicholas227** [comment]
Impromperly formatted, please submit again.

**Comment by Nicholas227** [comment]
Impromperly formatted, please submit again.

**Comment by Nit123** [comment]
I think the idea is that the resume is in your mind?

**Comment by Nicholas227** [comment]
Impromperly formatted, please submit again.
